### PR TITLE
GH-86: Fix & Improvement around parse and import for conversation

### PR DESCRIPTION
**Pull request by killix**

### CODE REVIEW

**Comment by killix** [comment]
hmm test failed, 
Las commit generate this issue is about "Variable Length Wildcards" with 2 digits case, if you have chance to look before me it's great!

**Comment by silentrob** [comment]
I'm reviewing why the change in regex is breaking the tests.. that seems kinda low risk.

**Comment by silentrob** [comment]
Are you able to skip the /test/script.js tests and try running the /test/continue.js tests. These should pass with this change, but Im not seeing any change.

**Comment by silentrob** [comment]
Also, we don't need the raw, input and trigger, they all seem to be the same anyway. I believe the trigger was the pre-baked regex (previous to 0.5.x). I say we simplify it down to just one field, unless you can think of a reason to keep the other one or two...

**Comment by killix** [comment]
I not really understand [regex not work](https://regex101.com/r/vW2zZ1/1) not work but  [regex work](https://regex101.com/r/vW2zZ1/3). For me the good regex is ```/\*(~[0-9]{0,2}\s?)/g```. But may be i have forget something.

**Comment by silentrob** [comment]
That site is amazing. I was using http://rubular.com/r/M51N2gpElS previously - but it was for ruby style regular expressions.

**Comment by silentrob** [comment]
Okay, Ive gotten to the bottom of the regex. {0,x} is too greedy, it needs to be {1,2} and all tests pass.

{0,x} matches on just the "*" which is not the correct behaviour. Keep in mind the regexp is being updated all the way down that function, so previous mutations add a "*" in the regexp from a previous replace.

**Comment by killix** [comment]
i understand. Thanks

**Comment by silentrob** [comment]
Whoops. one step forward and two steps back. I removed my cached json file and was able to repo this as well..  trigger.trigger is undefined. Im certain this is related to rolling back `17b4c69`

**Comment by killix** [comment]
yes i just look that...

**Comment by killix** [comment]
ok, now it's ok ;) sorry for the noise...

**Comment by silentrob** [comment]
Thanks so much for all your work on this. I will bring the other tests online and test the convo behaviour. What email would you like to be added to the contributors list?

**Comment by killix** [comment]
i'd just send you an email ;)

**Pull request merged**
