### PR TITLE
fix the conversation reply scope

### PR DESCRIPTION
**Pull request by killix**
All seems work with multiple conversations:

```
+ i went to highschool
- did you finish ?
	  + *
	  % did you finish ?
	  - i went to university
	  - what was it like?


+ i like to travel
- have you been to Madird?
  + ~yes *
  % have you been to Madird?
  - Madird is amazing.
  + *
  % Madird is amazing.
  - well well

  + ~no *
  % have you been to Madird?
  - Madird is my favorite city.

 + ~emohello [*~2]
- Hi!
- Hi, how are you?
- How are you?
- Hello
- Howdy
- Ola

> topic:system topic_name (who knock)
    + knock knock
    - who is there?
    - who isw trthere?
    - who isq tshere?
    - who?
        + *1
        // % support 'who is there?' or 'who *' (match with all reply 'who') or '*' (wildcard)
        % who *
        - <cap> who?


            + *1
            % <cap> who?
            - LOL! <cap>! That's funny!
< topic
```
the json generated:

```json
{
    "topics": {
        "random": {
            "flags": [],
            "keywords": []
        },
        "topic_name": {
            "flags": [
                "system"
            ],
            "keywords": [
                "who",
                "knock"
            ]
        }
    },
    "gambits": {
        "t8srtdi5": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false
            },
            "replys": [
                "uimPQTgN"
            ],
            "redirect": null,
            "trigger": "I went to highschool",
            "raw": "I went to highschool"
        },
        "FWiNxhbG": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false,
                "conversations": [
                    "uimPQTgN"
                ]
            },
            "replys": [
                "JUYrRYtp",
                "FvkM9aCu"
            ],
            "redirect": null,
            "trigger": "(?:.*?)",
            "raw": "*"
        },
        "hUPgGPxT": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false
            },
            "replys": [
                "5yPI27Ru"
            ],
            "redirect": null,
            "trigger": "I like to travel",
            "raw": "I like to travel"
        },
        "2BzxlAu5": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false,
                "conversations": [
                    "5yPI27Ru"
                ]
            },
            "replys": [
                "EF5PJ72t"
            ],
            "redirect": null,
            "trigger": "~yes(?:.*\\s?)",
            "raw": "~yes *"
        },
        "9nCpdKGj": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false,
                "conversations": [
                    "EF5PJ72t"
                ]
            },
            "replys": [
                "2RHDMEyg"
            ],
            "redirect": null,
            "trigger": "(?:.*?)",
            "raw": "*"
        },
        "SVlSPpb7": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false,
                "conversations": [
                    "5yPI27Ru"
                ]
            },
            "replys": [
                "U6ZATjRu"
            ],
            "redirect": null,
            "trigger": "~no(?:.*\\s?)",
            "raw": "~no *"
        },
        "7VXcohV1": {
            "topic": "random",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false
            },
            "replys": [
                "6ezO8WNi",
                "08jV42Op",
                "VIEwsMC5",
                "tEVhbDSu",
                "UBzOLczj",
                "7C9iOIbt"
            ],
            "redirect": null,
            "trigger": "~emohello(?:\\s*(\\s?(?:[\\w-]*\\s?){0,2})\\s*|\\s*)",
            "raw": "~emohello [*~2]"
        },
        "EvRlYsTS": {
            "topic": "topic_name",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false
            },
            "replys": [
                "pcvjt62F",
                "bekuoGlE",
                "guw3Nze4",
                "PmNIadI2"
            ],
            "redirect": null,
            "trigger": "knock knock",
            "raw": "knock knock"
        },
        "r3OsnBrb": {
            "topic": "topic_name",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false,
                "conversations": [
                    "pcvjt62F",
                    "bekuoGlE",
                    "guw3Nze4",
                    "PmNIadI2"
                ]
            },
            "replys": [
                "ouywHMUo"
            ],
            "redirect": null,
            "trigger": "(\\S+(:?\\s+\\S+){0})",
            "raw": "*1"
        },
        "TmPa6y3y": {
            "topic": "topic_name",
            "options": {
                "isQuestion": false,
                "qType": false,
                "qSubType": false,
                "filter": false,
                "conversations": [
                    "ouywHMUo"
                ]
            },
            "replys": [
                "C2ZrmXNg"
            ],
            "redirect": null,
            "trigger": "(\\S+(:?\\s+\\S+){0})",
            "raw": "*1"
        }
    },
    "replys": {
        "uimPQTgN": "did you finish ?",
        "JUYrRYtp": "i went to university",
        "FvkM9aCu": "what was it like?",
        "5yPI27Ru": "have you been to Madird?",
        "EF5PJ72t": "Madird is amazing.",
        "2RHDMEyg": "well well",
        "U6ZATjRu": "Madird is my favorite city.",
        "6ezO8WNi": "Hi!",
        "08jV42Op": "Hi, how are you?",
        "VIEwsMC5": "How are you?",
        "tEVhbDSu": "Hello",
        "UBzOLczj": "Howdy",
        "7C9iOIbt": "Ola",
        "pcvjt62F": "who is there?",
        "bekuoGlE": "who isw trthere?",
        "guw3Nze4": "who isq tshere?",
        "PmNIadI2": "who?",
        "ouywHMUo": "<cap> who?",
        "C2ZrmXNg": "LOL! <cap>! That's funny!"
    },
    "checksums": {
        "./topics/main.ss": "68c2182e9678430e46a4324607f8602a83f7b195"
    }
}
```
and the copy of bot chat : 
```
You> hi

Bot> How are you?
You> i like to travel

Bot> have you been to Madird?
You> yes

Bot> Madird is amazing.
You> not really

Bot> well well
You> i went to highschool

Bot> did you finish ?
You> yes

Bot> what was it like?
You> knock knock

Bot> who isq tshere?
You> kill

Bot> kill who?
You> ix

Bot> LOL! ix! That's funny!
You> Connection closed by foreign host.
```

### CODE REVIEW

**Comment by killix** [comment]
the test failed but seems not generated by my commit.

```
      ✓ should continue (2298ms)
      ✓ should continue 2 - yes (1325ms)
      ✓ should continue 3 - no (1387ms)
      ✓ should continue Sorted - A (1271ms)
      1) should continue Sorted - B


  4 passing (13s)
  1 failing

  1) Super Script Continue System Match and continue should continue Sorted - B:

      Uncaught AssertionError: expected 'blue is mine too.' to equal 'I hate that color.'
      + expected - actual

      +"I hate that color."
      -"blue is mine too."

      at test/continue.js:54:32
      at index.js:238:16
      at Promise.<anonymous> (index.js:116:18)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
```

**Comment by silentrob** [comment]
Ya I think I beat you to the punch on this one. If you want to rebase my changes I will pull in your changes.

**Comment by silentrob** [comment]
And I actually didn't get a fix for that last broken test, I just re-ordered the script. It will have to be something I cycle back too. It is an edge case anyway.

**Comment by killix** [comment]
ok, conflict is resolve now.

**Comment by silentrob** [comment]
What a day! Thanks again for all your help today.

**Comment by killix** [comment]
welcome ;)

**Pull request merged**
